[CmdletBinding()]
param(
    [ValidateSet('', 'x86_64-pc-windows-msvc', 'x86_64-pc-windows-gnu', 'x86_64-pc-windows-gnullvm')]
    [string]$Target = '',
    [switch]$Force
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$manifest = Get-Content -LiteralPath (Join-Path $projectRoot 'Cargo.toml') -Raw -Encoding UTF8
$packageSection = [regex]::Match($manifest, '(?ms)^\[package\]\s*\r?\n(.*?)(?=^\[|\z)').Groups[1].Value
$version = [regex]::Match($packageSection, '(?m)^version\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)"\s*$').Groups[1].Value
if (-not $version) { throw 'A numeric package version is required.' }
$effectiveTarget = $Target
if (-not $effectiveTarget -and
    (Test-Path -LiteralPath (Join-Path $projectRoot '.tools\cargo\bin\cargo.exe')) -and
    (Test-Path -LiteralPath (Join-Path $projectRoot '.tools\llvm-mingw-20260826-ucrt-x86_64\bin\x86_64-w64-mingw32-clang.exe'))) {
    $effectiveTarget = 'x86_64-pc-windows-gnullvm'
}
& (Join-Path $PSScriptRoot 'build.ps1') -Task Verify -Configuration Release -Target $effectiveTarget
$releasePath = Join-Path $projectRoot 'target'
if ($effectiveTarget) { $releasePath = Join-Path $releasePath $effectiveTarget }
$exePath = Join-Path $releasePath 'release\tokwatch.exe'
$bytes = [IO.File]::ReadAllBytes($exePath)
if ($bytes.Length -lt 64 -or [BitConverter]::ToUInt16($bytes, 0) -ne 0x5A4D) { throw 'The application is not a Windows PE executable.' }
$peOffset = [BitConverter]::ToInt32($bytes, 0x3C)
if ($peOffset -lt 0 -or $peOffset -gt $bytes.Length - 6 -or
    [BitConverter]::ToUInt32($bytes, $peOffset) -ne 0x00004550 -or
    [BitConverter]::ToUInt16($bytes, $peOffset + 4) -ne 0x8664) { throw 'The installer requires a Windows x64 application payload.' }

$verificationRoot = Join-Path $projectRoot '.verification'
$distRoot = Join-Path $projectRoot 'dist'
$outputPath = Join-Path $distRoot "v$version"
foreach ($directory in @($verificationRoot, $distRoot, $outputPath)) {
    $full = [IO.Path]::GetFullPath($directory)
    if (-not $full.StartsWith($projectRoot + '\', [StringComparison]::OrdinalIgnoreCase)) { throw 'Output must stay inside the project.' }
    if (Test-Path -LiteralPath $full) {
        $item = Get-Item -LiteralPath $full -Force
        if (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw "Output must use ordinary directories: $full" }
    }
}
$compiler = & (Join-Path $PSScriptRoot 'bootstrap-installer.ps1')
$stage = Join-Path $verificationRoot ('installer-package-' + [Guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($stage) | Out-Null
& $compiler '/Q' ("/DProjectRoot=$projectRoot") ("/DAppVersion=$version") ("/DSourceExe=$exePath") ("/O$stage") (Join-Path $projectRoot 'installer\TokWatch.iss')
if ($LASTEXITCODE -ne 0) { throw 'Installer compilation failed.' }
$name = "TokWatch-Setup-v$version-windows-x64.exe"
$built = Join-Path $stage $name
$destination = Join-Path $outputPath $name
$hash = (Get-FileHash -LiteralPath $built -Algorithm SHA256).Hash.ToLowerInvariant()
if (Test-Path -LiteralPath $destination) {
    $item = Get-Item -LiteralPath $destination -Force
    if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Installer destination must be an ordinary file.' }
    if (-not $Force -and (Get-FileHash -LiteralPath $destination).Hash.ToLowerInvariant() -ne $hash) { throw 'A different installer exists. Use -Force to replace it.' }
}
# Remove only names generated by the previous portable packaging process.
$legacy = @('TokWatch.exe', "TokWatch-v$version-windows-x64.zip", 'SHA256SUMS.txt', 'README.txt', 'LICENSE')
foreach ($old in $legacy) {
    $path = Join-Path $outputPath $old
    if (Test-Path -LiteralPath $path) {
        $item = Get-Item -LiteralPath $path -Force
        if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Legacy package artifacts must be ordinary files.' }
        if (-not $Force) { throw 'Portable artifacts remain. Use -Force to replace them with the installer.' }
    }
}
[IO.Directory]::CreateDirectory($outputPath) | Out-Null
Copy-Item -LiteralPath $built -Destination $destination -Force
foreach ($old in $legacy) {
    $path = Join-Path $outputPath $old
    if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
}
Write-Output "Installer: $destination"
Write-Output "SHA256: $hash"